### ISSUE TITLE
Investigate strict trimesh pin

### ISSUE THREAD

**Issue by traversaro** [conda-forge/brax-feedstock#6]
### Comment:

The upstream brax setup.py has a strict trimesh pin added in https://github.com/google/brax/commit/bf5bbe424e13db9c6b8a98244dcc20742ee6bad1 . Indeed, back in https://github.com/conda-forge/brax-feedstock/pull/4 I tried to ignore the pin, and some tests (unfortunatly I do not remember which one, and the builg log is now gone) were failing. However, such strict pins are a bit problematic as they may create problems for users that either directly or indirectly require a newer trimesh.
It does not make sense to prevent the release of new version of brax in conda-forge, so for now we keep the strict pin, but it would be great to have at least an upstream issue in trimesh to refer to.

**Comment by traversaro** [comment]
I added the pin in https://github.com/conda-forge/brax-feedstock/pull/5 to pass CI. @erikfrey do you have any insight on the need for the pin, and do you know if there is any issue in trimesh that trackes the problem/bug for which it is necessary to pin trimesh to `3.9.35`.

**Comment by erikfrey** [comment]
Hi @traversaro - this pin is due to the way we organize code internally.  Our internal system has this old version of trimesh and it's difficult to upgrade, so we can guarantee we work against this version.  Newer versions of trimesh have breaking API changes so unfortunately it would be difficult to unpin.

Please let us know if this ever becomes an acute problem and we'll escalate.

**Comment by traversaro** [comment]
> Hi @traversaro - this pin is due to the way we organize code internally.  Our internal system has this old version of trimesh and it's difficult to upgrade, so we can guarantee we work against this version.  Newer versions of trimesh have breaking API changes so unfortunately it would be difficult to unpin.
> 
> Please let us know if this ever becomes an acute problem and we'll escalate.

Thanks! At the moment it is not a big problem, I wanted just to make sure the reason for the pin is documented somewhere, if the pin creates problem I will report them, thanks!

**Comment by traversaro** [comment]
This was fixed upstream in brax 0.9.2 (see https://github.com/google/brax/commit/9e14acb7fd2697236eac7ec8df6d94579dab8123#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7), so we can close this once we merge https://github.com/conda-forge/brax-feedstock/pull/9 .

**Comment by traversaro** [comment]
Fixed by the 0.9.2 update.
